[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20.19.0"
  NPM_FLAGS = "--legacy-peer-deps"
  CI = "false"

# Handle SPA routing - redirect all routes to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
